export const DEFAULT_TABS = [
  { id: 'gear',     label: 'gear' },
  { id: 'hygiene',  label: 'hygiene & meds' },
  { id: 'family',   label: 'family' },
  { id: 'house',    label: 'house prep' },
  { id: 'confirms', label: 'travel confirms' },
  { id: 'depart',   label: 'departure' },
]

export const DEFAULT_ITEMS = [
  // ── gear ──────────────────────────────────────────────────────────────────
  { tab: 'gear', category: 'id / $',         name: 'passport',                  critical: true,  tags: ['international'] },
  { tab: 'gear', category: 'id / $',         name: 'license',                   critical: true,  tags: ['always'] },
  { tab: 'gear', category: 'id / $',         name: 'cash',                      critical: false, tags: [] },
  { tab: 'gear', category: 'id / $',         name: 'insurance card (car)',       critical: false, tags: [] },
  { tab: 'gear', category: 'id / $',         name: 'insurance (medical)',        critical: true,  tags: ['always'] },
  { tab: 'gear', category: 'id / $',         name: 'aaa card',                  critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'work computer',             critical: false, tags: ['work'] },
  { tab: 'gear', category: 'electronics',    name: 'personal computer',         critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'tablet',                    critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'phone',                     critical: true,  tags: ['always'] },
  { tab: 'gear', category: 'electronics',    name: 'kindle',                    critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'headphones (over ear)',      critical: false, tags: ['flight'] },
  { tab: 'gear', category: 'electronics',    name: 'headphones (in ear)',        critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'wireless speaker',          critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'portable batteries',        critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'computer charger (work)',   critical: false, tags: ['work'] },
  { tab: 'gear', category: 'electronics',    name: 'computer charger (personal)',critical: false, tags: [] },
  { tab: 'gear', category: 'electronics',    name: 'charging cables',           critical: true,  tags: ['always'] },
  { tab: 'gear', category: 'electronics',    name: 'digital watch',             critical: false, tags: [] },
  { tab: 'gear', category: 'shoes',          name: 'athletic',                  critical: false, tags: [] },
  { tab: 'gear', category: 'shoes',          name: 'hiking',                    critical: false, tags: ['hiking'] },
  { tab: 'gear', category: 'shoes',          name: 'sandals',                   critical: false, tags: ['beach'] },
  { tab: 'gear', category: 'shoes',          name: 'inserts',                   critical: false, tags: [] },
  { tab: 'gear', category: 'shoes',          name: 'dress',                     critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'socks',          name: 'athletic',                  critical: true,  tags: [] },
  { tab: 'gear', category: 'socks',          name: 'dress',                     critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'underwear',      name: 'boxers',                    critical: true,  tags: [] },
  { tab: 'gear', category: 'underwear',      name: 'boxers (white)',            critical: false, tags: [] },
  { tab: 'gear', category: 'underwear',      name: 'compression shorts',        critical: false, tags: [] },
  { tab: 'gear', category: 'accessories',    name: 'wedding ring',              critical: true,  tags: [] },
  { tab: 'gear', category: 'accessories',    name: 'watch (dress)',             critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'accessories',    name: 'sunglasses',                critical: false, tags: ['beach'] },
  { tab: 'gear', category: 'accessories',    name: 'baseball hat',              critical: false, tags: [] },
  { tab: 'gear', category: 'accessories',    name: 'sun hat',                   critical: false, tags: ['beach'] },
  { tab: 'gear', category: 'accessories',    name: 'belt (dress)',              critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'accessories',    name: 'belt (cloth)',              critical: false, tags: [] },
  { tab: 'gear', category: 'luggage & car',  name: 'luggage tags / ids',        critical: false, tags: [] },
  { tab: 'gear', category: 'luggage & car',  name: 'toll coins',                critical: false, tags: [] },
  { tab: 'gear', category: 'shorts',         name: 'athletic',                  critical: false, tags: [] },
  { tab: 'gear', category: 'shorts',         name: 'dress',                     critical: false, tags: [] },
  { tab: 'gear', category: 'shorts',         name: 'bathing suit',              critical: false, tags: ['beach'] },
  { tab: 'gear', category: 'pants',          name: 'jeans',                     critical: false, tags: [] },
  { tab: 'gear', category: 'pants',          name: 'linen',                     critical: false, tags: ['beach'] },
  { tab: 'gear', category: 'pants',          name: 'dress / chinos',            critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'pants',          name: 'golf',                      critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'pants',          name: 'dad pants',                 critical: false, tags: [] },
  { tab: 'gear', category: 'pants',          name: 'sweats',                    critical: false, tags: [] },
  { tab: 'gear', category: 'pants',          name: 'sleep',                     critical: false, tags: [] },
  { tab: 'gear', category: 'shirts (short)', name: 't-shirt w/ buttons',        critical: false, tags: [] },
  { tab: 'gear', category: 'shirts (short)', name: 't-shirts w/o buttons',      critical: false, tags: [] },
  { tab: 'gear', category: 'shirts (short)', name: 'polos',                     critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'shirts (short)', name: 'collared button downs',     critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'shirts (short)', name: 'swim shirts',               critical: false, tags: ['beach'] },
  { tab: 'gear', category: 'shirts (long)',  name: 'collared button down',      critical: false, tags: ['formal'] },
  { tab: 'gear', category: 'shirts (long)',  name: 'henley button down',        critical: false, tags: [] },
  { tab: 'gear', category: 'shirts (long)',  name: 'light sweatshirt / hoodie', critical: false, tags: [] },
  { tab: 'gear', category: 'shirts (long)',  name: 'heavier sweatshirt / hoodie',critical: false, tags: [] },
  { tab: 'gear', category: 'suit-specific',  name: 'jacket',                    critical: false, tags: ['formal', 'wedding'] },
  { tab: 'gear', category: 'suit-specific',  name: 'tie',                       critical: false, tags: ['formal', 'wedding'] },
  { tab: 'gear', category: 'suit-specific',  name: 'tie clip',                  critical: false, tags: ['formal', 'wedding'] },
  { tab: 'gear', category: 'suit-specific',  name: 'cuff links',                critical: false, tags: ['formal', 'wedding'] },
  { tab: 'gear', category: 'suit-specific',  name: 'pocket square',             critical: false, tags: ['formal', 'wedding'] },
  { tab: 'gear', category: 'jackets',        name: 'rain',                      critical: false, tags: [] },
  { tab: 'gear', category: 'jackets',        name: 'winter',                    critical: false, tags: [] },
  { tab: 'gear', category: 'golf',           name: 'clubs',                     critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'golf',           name: 'travel case',               critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'golf',           name: 'golf shoes',                critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'golf',           name: 'tees',                      critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'golf',           name: 'balls',                     critical: false, tags: ['golf'] },
  { tab: 'gear', category: 'golf',           name: 'glove',                     critical: false, tags: ['golf'] },

  // ── hygiene & meds ────────────────────────────────────────────────────────
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'toothbrush',            critical: true,  tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'toothpaste',            critical: true,  tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'mouthwash',             critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'floss',                 critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'deodorant',             critical: true,  tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'nail clippers',         critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'foot deodorant',        critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'neti pot',              critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'saline packets',        critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'cologne',               critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'nose trimmer',          critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'retainer',              critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'shaver (razor & blades)',critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'shaver (philips - normal)',critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'shaver (philips - sensitive)',critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'shaver (rotating)',     critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'shaving cream',         critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'cauterizing stick',     critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'tweezers',              critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'chapstick',             critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'tissues',               critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'antiseptic gel',        critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'antiseptic wipes',      critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'q-tips',                critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'first aid kit',         critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'lube',                  critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'vibrator',              critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'lotion (night)',        critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'lotion (day)',          critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'hair cream',            critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (travel)', name: 'eye cream',             critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'shave (face)',      critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'shave (neck / back)',critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'shave (balls)',     critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'clip nails',        critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'pluck eyebrows',    critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'clean ears',        critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'trim sideburns',    critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'trim nose hair',    critical: false, tags: [] },
  { tab: 'hygiene', category: 'hygiene (pre-travel)', name: 'trim ear hair',     critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'lactaid',                 critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'advil',                   critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'tylenol',                 critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'allegra',                 critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'antacids',                critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'vitamins',                critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'diet pills',              critical: false, tags: [] },
  { tab: 'hygiene', category: 'meds',           name: 'zoloft',                  critical: true,  tags: ['always'] },
  { tab: 'hygiene', category: 'meds',           name: 'sunscreen',               critical: false, tags: ['beach'] },
  { tab: 'hygiene', category: 'meds',           name: 'caffeine packets',        critical: false, tags: [] },

  // ── family ────────────────────────────────────────────────────────────────
  { tab: 'family', category: 'whitney',         name: 'passport',                critical: true,  tags: ['international'] },
  { tab: 'family', category: 'whitney',         name: 'license',                 critical: true,  tags: [] },
  { tab: 'family', category: 'whitney',         name: 'wallet',                  critical: true,  tags: [] },
  { tab: 'family', category: 'whitney',         name: 'phone (personal)',        critical: true,  tags: [] },
  { tab: 'family', category: 'whitney',         name: 'phone (work)',            critical: false, tags: ['work'] },
  { tab: 'family', category: 'whitney',         name: 'computer (work)',         critical: false, tags: ['work'] },
  { tab: 'family', category: 'whitney',         name: 'mouse',                   critical: false, tags: ['work'] },
  { tab: 'family', category: 'whitney',         name: 'chargers',                critical: true,  tags: [] },
  { tab: 'family', category: 'whitney',         name: 'salt',                    critical: false, tags: [] },
  { tab: 'family', category: 'whitney',         name: 'road pop',                critical: false, tags: [] },
  { tab: 'family', category: 'whitney',         name: 'kindle',                  critical: false, tags: [] },
  { tab: 'family', category: 'whitney',         name: 'sunglasses',              critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'epi-pen',                 critical: true,  tags: [] },
  { tab: 'family', category: 'brady',           name: 'life vac',                critical: true,  tags: [] },
  { tab: 'family', category: 'brady',           name: 'portable potty',          critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'sound machine',           critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'shower gel',              critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'passport',                critical: true,  tags: ['international'] },
  { tab: 'family', category: 'brady',           name: 'snacks',                  critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'medicines',               critical: true,  tags: [] },
  { tab: 'family', category: 'brady',           name: 'diapers',                 critical: true,  tags: [] },
  { tab: 'family', category: 'brady',           name: 'wipes',                   critical: true,  tags: [] },
  { tab: 'family', category: 'brady',           name: 'poop bags',               critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'spare clothes',           critical: true,  tags: [] },
  { tab: 'family', category: 'brady',           name: 'water',                   critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'travel toys',             critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'situational clothes',     critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'weather specific clothes',critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'toy batteries',           critical: false, tags: [] },
  { tab: 'family', category: 'brady',           name: 'neigh (favorite toy)',    critical: true,  tags: [] },
  { tab: 'family', category: 'dogs',            name: 'pills',                   critical: true,  tags: [] },
  { tab: 'family', category: 'dogs',            name: 'dry food',                critical: true,  tags: [] },
  { tab: 'family', category: 'dogs',            name: 'wet food',                critical: false, tags: [] },
  { tab: 'family', category: 'dogs',            name: 'bones',                   critical: false, tags: [] },
  { tab: 'family', category: 'cats',            name: 'cat feeder (tested)',     critical: true,  tags: [] },
  { tab: 'family', category: 'cats',            name: 'cat feeder (tipping support)',critical: false, tags: [] },
  { tab: 'family', category: 'cats',            name: 'water',                   critical: true,  tags: [] },
  { tab: 'family', category: 'cats',            name: 'decoy food',              critical: false, tags: [] },

  // ── house prep ───────────────────────────────────────────────────────────
  { tab: 'house', category: 'house prep',       name: 'water shutoff',           critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'check basement drain',    critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'flush toilets',           critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'door lock (front)',       critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'door lock (side garage)', critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'door lock (sunroom)',     critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'battery test (side garage)',critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'lights (on or off)',      critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'trash / recycling (out of house)',critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'trash / recycling (to curb)',critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'run dishwasher',          critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'text susan / dan',        critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'garage cam (check)',      critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'space heaters (off)',     critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'fireplaces (off)',        critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'range top (off)',         critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'oven (off)',              critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'lock cars',               critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'hide jewelry',            critical: false, tags: [] },
  { tab: 'house', category: 'house prep',       name: 'garage door down',        critical: true,  tags: [] },
  { tab: 'house', category: 'house prep',       name: 'garage door opener (to sitter)',critical: false, tags: [] },
  { tab: 'house', category: 'car & traffic',    name: 'gas (fill car)',          critical: false, tags: [] },
  { tab: 'house', category: 'car & traffic',    name: 'calculate departure time',critical: false, tags: [] },
  { tab: 'house', category: 'car & traffic',    name: 'check traffic',           critical: false, tags: [] },

  // ── travel confirms ──────────────────────────────────────────────────────
  { tab: 'confirms', category: 'travel confirms', name: 'download airline app',  critical: false, tags: [] },
  { tab: 'confirms', category: 'travel confirms', name: 'flight check-in',       critical: true,  tags: [] },
  { tab: 'confirms', category: 'travel confirms', name: 'hotel confirmation',    critical: true,  tags: [] },
  { tab: 'confirms', category: 'travel confirms', name: 'rental car confirmation',critical: false, tags: [] },
  { tab: 'confirms', category: 'travel confirms', name: 'dogs (anti-anxiety meds)',critical: false, tags: [] },
]

export const FINAL_CHECKLIST_ITEMS = [
  { tab: 'depart', category: 'final checklist', name: 'wallet',        critical: true,  tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'phones',        critical: true,  tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'luggage',       critical: true,  tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'bookbags',      critical: false, tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'passports',     critical: true,  tags: ['international'] },
  { tab: 'depart', category: 'final checklist', name: 'license',       critical: true,  tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'garage door',   critical: true,  tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'critical meds', critical: true,  tags: [] },
  { tab: 'depart', category: 'final checklist', name: 'work computer', critical: false, tags: ['work'] },
]



export const DEFAULT_DEPARTURE = {
  departureTime: '18:00',
  boardingCutoff: 10,
  boardingDuration: 30,
  barTime: 45,
  barToGate: 5,
  securityDuration: 20,
 bagCheckDuration: 15,
  bagCheckToSecurity: 10,
  securityToBar: 10,
  parkingToBagCheck: 20,
  commuteDuration: 35,
  wakeToLeave: 60,
  hiddenMilestones: [],
}
